# Generated by Django 4.1.7 on 2023-03-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_author_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'olke', 'verbose_name_plural': 'olkeler'},
        ),
    ]
